circuit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^histoire/(?P<pk>\d+)/$', views.DetailMot.as_view(), name='DetailMot'),
    url(r'^supprimer/(?P<pk>\d+)/$', views.Circuitdelete.as_view(), name="Circuitdelete"),
    url(r'^supprimer/prisencharge/(?P<pk>\d+)/$', views.PrisenchargeDeleteView.as_view(), name="PrisenchargeDeleteView"),
    url(r'^modifier/(?P<pk>\d+)/$', views.CircuitUpdate.as_view(), name="CircuitUpdate"),
    url(r'^nos_circuit/(?P<pk>\d+)/$', views.CircuitDetail.as_view(), name="CircuitDetail"),
    url(r'^info/modifier/(?P<pk>\d+)/$', views.HomeUpdate.as_view(), name='HomeUpdate'),
    url(r'^histoire/modifier/(?P<pk>\d+)/$', views.UpdateteMot.as_view(), name='UpdateteMot'),
    url(r'^prisencharge/modifier/(?P<pk>\d+)/$', views.PrisenchargeUpdate.as_view(), name='PrisenchargeUpdate'),
    url(r'^infos/create/$', views.HomeInfo.as_view(), name='HomeInfor'),
    url(r'^prisencharge/Ajouter/$', views.Prisencharge.as_view(), name='Prisencharge'),
    url(r'^prisencharge/$', views.PrisenchargeList.as_view(), name='PrisenchargeList'),
    url(r'^ajouter/$',views.CirctuiCreate.as_view(),name="Circtuitest"),
    url(r'^$', views.CircuitList.as_view(), name="CircuitList"),
]

moulamoulatit/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from moulamoulatit import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$/', include('circuit.urls', namespace="moulatitcircuit")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% block css %}

    {% endblock css %}
    <link href="https://fonts.googleapis.com/css?family=Cairo:300,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

</head>
<body>
    <nav id="homenav">
        <div class="mycontainer">
            <a href='{%url 'moulatitcircuit:CircuitList'%}' id="logolink"><img src="{{footer.logo.url}}" id="logo" alt="Moulamoulatit logo"> {% if footer.logo_name %}{{ footer.logo_name }}{% endif %} </a>
            <ul>
                <li><a href="{%url 'moulatitcircuit:CircuitList'%}">Accueil</a></li>
                <li><a href="{%url 'moulatitcircuit:CircuitList'%}#Nosircuit">Nos Circuits</a></li>
                <li><a href="{%url 'moulatitcircuit:DetailMot' pk=1%}">Histoire</a></li>
                <li><a href="{%url 'moulatitcircuit:PrisenchargeList'%}#PrisOncharge">Prise en charge</a></li>
                <li><a href="{%url 'moulatitcircuit:PrisenchargeList'%}">Infos-voyage</a></li>
                <li><a href="#contact">Contact</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'moulatitcircuit:Prisencharge' %}">Ajouter Des Infos</a></li>
                    <li><a href="{% url 'moulatitcircuit:UpdateteMot' pk=1 %}">Modifier Histoire</a></li>
                    <li><a href="{% url 'moulatitcircuit:Circtuitest' %}">Ajouter Un Circuit</a></li>
                    <li><a href="{% url 'moulatitcircuit:HomeUpdate' pk=1 %}">Modifier Les Infos</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="homemarg"></div>
    {% block content %}

    {% endblock content%}
<footer  id="contact">
    <div class="mycontainer">
        <div class="divers  col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <div class="content">
                <h1>Social</h1>
                <p>Retrouvez nous sur les réseaux sociaux</p>
                <a href="{{ footer.facebook }}" class="btneffect">Facebook</a>
                <a href="{{ footer.Instagram }}" class="btneffect">Instagram</a>
            </div>
        </div>
        <div class="divers  col-xs-12 col-sm-4 col-md-4 col-lg-4">
           <div class="content">
            <h1>Cordonnées</h1>
            <p>Email: {{ footer.Email }}</p>
            <p>Fax : {{ footer.Fax }}</p>
            <p>Tèlephone: {{ footer.Mobile }}</p>
           </div>
        </div>
        <div class="divers  col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <div class="content">
                <h1>Adresse</h1>
                <p>{{ footer.Adress }}</p>
            </div>
        </div>
    </div>
</footer>
<div id="bg">
        {% if footer.img_1%}
            <div class="item" style="background:url('{{ footer.img_1.url }}')" id="img2"></div>
        {% endif %}
        {% if footer.img_2%}
            <div class="item" style="background:url('{{ footer.img_2.url }}')" id="img2"></div>
        {% endif %}
        {% if footer.img_3 %}
                <div class="item" style="background: url('{{ footer.img_3.url }}')" id="img3"></div>
        {% endif %}
<div class="overlay"></div>
</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block script %}

{% endblock script%}
<script src="{% static '/js/myapp.js' %}"></script>
    <script>
        i=$('.item').length-1;
        window.setInterval(function(){
            $('.item').eq(i).fadeOut();
            if (i ===0){
                i=$('.item').length-1;
                $('.item').fadeIn()
            }else {
                i--;
            }
        }, 3000);
    </script>
</body>
</html>