circuit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^histoire/(?P<pk>\d+)/$', views.DetailMot.as_view(), name='DetailMot'),
    url(r'^supprimer/(?P<pk>\d+)/$', views.Circuitdelete.as_view(), name="Circuitdelete"),
    url(r'^supprimer/prisencharge/(?P<pk>\d+)/$', views.PrisenchargeDeleteView.as_view(), name="PrisenchargeDeleteView"),
    url(r'^modifier/(?P<pk>\d+)/$', views.CircuitUpdate.as_view(), name="CircuitUpdate"),
    url(r'^nos_circuit/(?P<pk>\d+)/$', views.CircuitDetail.as_view(), name="CircuitDetail"),
    url(r'^info/modifier/(?P<pk>\d+)/$', views.HomeUpdate.as_view(), name='HomeUpdate'),
    url(r'^histoire/modifier/(?P<pk>\d+)/$', views.UpdateteMot.as_view(), name='UpdateteMot'),
    url(r'^prisencharge/modifier/(?P<pk>\d+)/$', views.PrisenchargeUpdate.as_view(), name='PrisenchargeUpdate'),
    url(r'^infos/create/$', views.HomeInfo.as_view(), name='HomeInfor'),
    url(r'^prisencharge/Ajouter/$', views.Prisencharge.as_view(), name='Prisencharge'),
    url(r'^prisencharge/$', views.PrisenchargeList.as_view(), name='PrisenchargeList'),
    url(r'^ajouter/$',views.CirctuiCreate.as_view(),name="Circtuitest"),
    url(r'^$', views.CircuitList.as_view(), name="CircuitList"),
]

moulamoulatit/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from moulamoulatit import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$/', include('circuit.urls', namespace="moulatitcircuit")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

circuit/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Circuit(models.Model):
    Titre = models.CharField(max_length=255)
    Description = models.TextField(null=True)
    def __str__(self):
        return self.Titre

    def get_absolute_url(self):
        return reverse('moulatitcircuit:CircuitDetail',kwargs={
            'pk':self.pk
        })

    def get_first_image(self):
        if self.imageupload_set.all().first():
            return self.imageupload_set.all().first().relationship.url
        else:
            return None

class CircuitParts(models.Model):
    titre_circuit = models.CharField(max_length=255)
    Description = models.TextField(null=True)
    class Meta:
        abstract = True

class CirctuiDetail(CircuitParts):
    Circuit = models.ForeignKey(Circuit)
    def __str__(self):
        return self.titre_circuit

class lesinfos(models.Model):
    titre = models.CharField(max_length=255)

    def __str__(self):
        return self.titre

class Prisencharche(CircuitParts):
    Infos = models.ForeignKey(lesinfos)

    def __str__(self):
        return self.titre_circuit

class ImageUpload(models.Model):
    relationship = models.ImageField(blank=False,null=False)
    x = models.FloatField(blank=False,null=False)
    y = models.FloatField(blank=False,null=False)
    width = models.FloatField(blank=False,null=False)
    height = models.FloatField(blank=False,null=False)
    bld = models.ForeignKey(Circuit, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return str(self.relationship)

    def get_img_url(self):
        return self.relationship.url()


class HomeDetail(models.Model):
    logo = models.ImageField()
    logo_name = models.CharField(max_length=255,blank=True,null=True)
    facebook = models.URLField(blank=True,null=True)
    Instagram = models.URLField(blank=True,null=True)
    Email = models.EmailField(blank=True,null=True)
    Fax = models.CharField(max_length=255,blank=True,null=True)
    Mobile = models.CharField(max_length=255,blank=True,null=True)
    Adress = models.CharField(max_length=255)
    img_1 = models.ImageField(blank=True,null=True)
    description1 = models.TextField(blank=True,null=True)
    img_2 = models.ImageField(blank=True,null=True)
    description2 = models.TextField(blank=True,null=True)
    img_3= models.ImageField(blank=True,null=True)
    description3 = models.TextField(blank=True,null=True)
    histoire = models.TextField(blank=True,null=True,verbose_name='Mots')
    def __str__(self):
        return self.Adress


class Mots(models.Model):
    titre = models.CharField(max_length=255)
    mots = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.titre

circuit/forms.py
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.forms import ModelForm, inlineformset_factory, modelformset_factory
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Circuit, CirctuiDetail, ImageUpload, Prisencharche, lesinfos
from PIL import Image


class Cicuitform(ModelForm):
    class Meta:
        model = Circuit
        exclude = ()


class CirctuiForm(ModelForm):
    class Meta:
        model = CirctuiDetail
        exclude =()


class PrisencharcheForm(ModelForm):
    class Meta:
        model = Prisencharche
        exclude =()

class FamilyMemberForm(ModelForm):
    class Meta:
        model = ImageUpload
        exclude = ()



class PhotoForm(forms.ModelForm):

    x = forms.FloatField(widget=forms.HiddenInput)
    y = forms.FloatField(widget=forms.HiddenInput)
    height = forms.FloatField(widget=forms.HiddenInput)
    width = forms.FloatField(widget=forms.HiddenInput)

    class Meta:
        model = ImageUpload
        fields = ('relationship', 'x','y','height','width',)

    def save(self,*args,**kwargs):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x > 0 or x <= 0:
            if y>0 or y<=0:
                if w > 0 or w <= 0:
                    if h > 0 or h <= 0:
                        image = Image.open(photo.relationship)
                        cropped_image = image.crop((x, y, w+x, h+y))
                        resized_image = cropped_image.resize((500, 700), Image.ANTIALIAS)
                        resized_image.save(photo.relationship.path)
                        return super(PhotoForm, self).save(*args, **kwargs)
        return super(PhotoForm, self).save(*args, **kwargs)


CircuitwithDetail = inlineformset_factory(Circuit, CirctuiDetail,form=CirctuiForm,extra=1)
CircuitwithPrisenCharge = inlineformset_factory(lesinfos, Prisencharche,form=PrisencharcheForm,extra=10)
FamilyMemberFormSet = inlineformset_factory(Circuit, ImageUpload,form=PhotoForm,extra=1)

circuit/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView, TemplateView

from .forms import CircuitwithDetail, FamilyMemberFormSet, CircuitwithPrisenCharge
from .models import Circuit, HomeDetail, lesinfos, Mots


class CirctuiCreate(LoginRequiredMixin,CreateView):
    model = Circuit
    fields = ['Titre','Description',]
    template_name = 'circtuit/form.html'

    def get_context_data(self, **kwargs):
        context = super(CirctuiCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['bookimage_form'] = CircuitwithDetail(self.request.POST)
            context['familymembers'] = FamilyMemberFormSet(self.request.POST,self.request.FILES)

        else:
            context['bookimage_form'] = CircuitwithDetail()
            context['familymembers'] = FamilyMemberFormSet()

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        bookimage_form = context['bookimage_form']
        familymembers = context['familymembers']
        if bookimage_form.is_valid() and familymembers.is_valid():
            print('is valid')
            self.object = form.save()
            bookimage_form.instance = self.object
            bookimage_form.save()
            familymembers.instance = self.object
            familymembers.save()
        else:
            return self.render_to_response(self.get_context_data(form=form))
        return super(CirctuiCreate, self).form_valid(form)


class CircuitUpdate(LoginRequiredMixin,UpdateView):
    model = Circuit
    fields = ['Titre','Description',]
    template_name = 'circtuit/form.html'

    def get_context_data(self, **kwargs):
        context = super(CircuitUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['bookimage_form'] = CircuitwithDetail(self.request.POST,instance=self.object)
            context['familymembers'] = FamilyMemberFormSet(self.request.POST,self.request.FILES, instance=self.object)
        else:
            context['bookimage_form'] = CircuitwithDetail(instance=self.object)
            context['familymembers'] = FamilyMemberFormSet(instance=self.object)
        return context


    def form_valid(self, form):
        context = self.get_context_data()
        bookimage_form = context['bookimage_form']
        familymembers = context['familymembers']
        with transaction.atomic():
            self.object = form.save()
            if bookimage_form.is_valid() and familymembers.is_valid():
                print("is valid")
                bookimage_form.instance = self.object
                bookimage_form.save()
                familymembers.instance = self.object
                familymembers.save()
        return super(CircuitUpdate, self).form_valid(form)


class Circuitdelete(LoginRequiredMixin,DeleteView):
    model = Circuit
    template_name = 'circtuit/delete.html'
    success_url = reverse_lazy('moulatitcircuit:CircuitList')


class CircuitList(ListView):
    model = Circuit
    template_name = 'circtuit/list.html'
    queryset = Circuit.objects.all().prefetch_related('imageupload_set')



class CircuitDetail(DetailView):
    model = Circuit
    template_name = 'circtuit/detail.html'





class HomeInfo(LoginRequiredMixin,CreateView):
    model = HomeDetail
    template_name = 'circtuit/myform.html'
    fields = ['logo','logo_name', 'facebook','Instagram','Email','Fax','Mobile','Adress','img_1','description1','img_2','description2','img_3','description3','histoire']
    success_url = ('.')


class HomeUpdate(LoginRequiredMixin,UpdateView):
    model = HomeDetail
    template_name = 'circtuit/myform.html'
    fields = ['logo', 'logo_name','facebook','Instagram','Email','Fax','Mobile','Adress','img_1','description1','img_2','description2','img_3','description3','histoire']
    success_url = ('.')

class Prisencharge(LoginRequiredMixin,CreateView):
    model = lesinfos
    fields = ['titre',]
    template_name = 'circtuit/myform.html'
    success_url = reverse_lazy('moulatitcircuit:PrisenchargeList')

    def get_context_data(self, **kwargs):
        context = super(Prisencharge, self).get_context_data(**kwargs)
        if self.request.POST:
            context['bookimage_form'] = CircuitwithPrisenCharge(self.request.POST)

        else:
            context['bookimage_form'] = CircuitwithPrisenCharge()

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        bookimage_form = context['bookimage_form']
        with transaction.atomic():
            self.object = form.save()
            if bookimage_form.is_valid() :
                bookimage_form.instance = self.object
                bookimage_form.save()
            else:
                return self.render_to_response(self.get_context_data(form=form))
        return super(Prisencharge, self).form_valid(form)


class PrisenchargeUpdate(LoginRequiredMixin,UpdateView):
    model = lesinfos
    fields = ['titre',]
    template_name = 'circtuit/myform.html'
    success_url = reverse_lazy('moulatitcircuit:PrisenchargeList')

    def get_context_data(self, **kwargs):
        context = super(PrisenchargeUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['bookimage_form'] = CircuitwithPrisenCharge(self.request.POST,instance=self.object)
        else:
            context['bookimage_form'] = CircuitwithPrisenCharge(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        bookimage_form = context['bookimage_form']

        with transaction.atomic():
            self.object = form.save()
            if bookimage_form.is_valid():
                print("is valid")
                bookimage_form.instance = self.object
                bookimage_form.save()

        return super(PrisenchargeUpdate, self).form_valid(form)

class PrisenchargeList(ListView):
    model = lesinfos
    template_name = 'circtuit/lesinfos.html'

class PrisenchargeDeleteView(LoginRequiredMixin,DeleteView):
    model = lesinfos
    template_name = 'circtuit/delete.html'
    success_url = reverse_lazy('moulatitcircuit:PrisenchargeList')


class UpdateteMot(LoginRequiredMixin,UpdateView):
    model = Mots
    fields = ('titre','mots',)
    template_name = 'circtuit/myform.html'
    success_url = reverse_lazy('moulatitcircuit:CircuitList')


class DetailMot(DetailView):
    model = Mots
    template_name = 'circtuit/mots.html'
    queryset = Mots.objects.all()

circuit/templates/circtuit/delete.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="allcontent mycontainer" style="color: #fff">
        <form action="" method="post">
            {% csrf_token %}
            <p>Êtes-vous sûr que Vous voulez supprimer {{ object }}</p>
            <a href="{{ object.get_absolute_url }}">Non</a>
            <input type="submit" value="Supprimer" style="background: #fff;color: #000;border: none; padding: 10px 20px">
        </form>
    </div>
{% endblock %}

circuit/templates/circtuit/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}

{% endblock %}
<link rel="stylesheet" href="{% static '/css/lightbox.css' %}">
{% block content %}
    <div class="allcontent">
    <div class="mycontainer circuitdetaill">
        <h1>{{ object.Titre }}</h1>
        <div class="linediveder"></div>
        {% for foo in object.circtuidetail_set.all %}
            <div class="circuitext col-xs-12 col-sm-12 col-md-6 col-lg-6 {% cycle 'class_left' 'class_right'%}">
                <h3>{{ foo.titre_circuit }}</h3>
                <p>{{ foo.Description|linebreaks }}</p>
            </div>
        {% endfor %}
    </div>
    <div class="linebreak "></div>
      <div class="gallery mycontainer">
        <div class="row">
            {% for foo in object.imageupload_set.all %}
                <div class="detail_gallerie col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    <img src="{{ foo.relationship.url }}" alt="{{ object.Titre }}">
                </div>
            {% endfor %}
        </div>
      </div>

                    {% if user.is_authenticated %}

        <a href="{% url 'moulatitcircuit:CircuitUpdate' pk=object.pk %}">Modifier</a>
        <a href="{% url 'moulatitcircuit:Circuitdelete' pk=object.pk %}">Supprimer</a>
        {% endif %}

    </div>
    <div class="lightbox">
        <i class="fa fa-times close-ico" aria-hidden="true"></i>
        <div class="lightboxcontainer">
            <img src="" id="gallery_lightbox"  alt="">
            <div  id="next"><i class="fa fa-angle-right" aria-hidden="true"></i></div>
            <div  id="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></div>
        </div>
    </div>
{% endblock %}
{% block script %}
{% endblock script %}

circuit/templates/circtuit/form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}

{% endblock title%}
{% block css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/3.1.3/cropper.min.css" rel="stylesheet">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock css%}

{% block content %}
    <div class="allcontent mycontainer" style="color: #fff">

        <form action="" method="post" enctype="multipart/form-data" class="circuitform">
        {% csrf_token %}
            <div class="inputstyle">
                {{ form.as_p }}
            </div>
            <img id="image_upload_preview" src="http://placehold.it/100x100" alt="your image" />

            <hr>
            <div  class="inputstyle ">
                <div id="wrapper" >
                {{ bookimage_form.management_form }}

                    {% for form in bookimage_form.forms %}
                        <div class="imgnum">

                        <div class="{% cycle row1 row2 %} formset_row">
                            {% for field in form.visible_fields %}
                               <th>{{ field.label|capfirst }}</th>
                                <div>
                                    {# Include the hidden fields in the form #}
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                </div>

                            {% endfor %}
                        </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <button type="button" id="costum_fs" class="btneffect">Ajouter un circuit</button>
                <div class="linebreak"></div>
            <hr>
             {{ familymembers.management_form }}

                    <div id="wrapper2">
                        {% for form in familymembers.forms %}
                            <div class="{% cycle row1 row2 %} formset_row">
                                {% for field in form.visible_fields %}
                                   {{ field.label|capfirst }}
                                    <td>
                                        {# Include the hidden fields in the form #}
                                        {% if forloop.first %}
                                            {% for hidden in form.hidden_fields %}
                                                {{ hidden }}
                                            {% endfor %}
                                        {% endif %}
                                        {{ field.errors.as_ul }}
                                        {{ field }}
                                    </td>

                                {% endfor %}
                            </div>
                    {% endfor %}
                    </div>

        <button type="button" id="costum_fs2" class="btneffect">Ajouter une photo</button>
        <div class="linebreak"></div>
        <input type="submit" id="subm" class="btneffect">
    </form>
    </div>
    <div class="modal fade" id="modalCrop">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title">Crop the photo</h4>
          </div>
          <div class="modal-body">
            <img src="" id="image" style="max-width: 100%;">
          </div>
          <div class="modal-footer">
            <div class="btn-group pull-left" role="group">
              <button type="button" class="btn btn-default js-zoom-in">
                <span class="glyphicon glyphicon-zoom-in"></span>
              </button>
              <button type="button" class="btn btn-default js-zoom-out">
                <span class="glyphicon glyphicon-zoom-out"></span>
              </button>
            </div>
            <button type="button" class="btn btn-default" id="never" data-dismiss="modal">Nevermind</button>
            <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}
{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/3.1.3/cropper.min.js"></script>
{% endblock script%}

circuit/templates/circtuit/lesinfos.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}

{% block content %}
    <div class="allcontent mycontainer" style="color: #fff">
        {% for foo in object_list %}
            <h1 style="text-align: center">{{ foo.titre }}</h1>
            <div class="linediveder"></div>
            <div class="row">
            {% for foo2 in foo.prisencharche_set.all %}
                <div class="circuitext col-xs-12 col-sm-12 col-md-6 col-lg-6 {% cycle 'class_left' 'class_right' %}">
                    <h3>{{foo2.titre_circuit}}</h3>
                    <p>{{foo2.Description|linebreaks}}</p>
                    <div class="linebreak"></div>
                </div>
            {% endfor %}
            {% if user.is_authenticated %}
                <div class="linebreak"></div>
                    <a href="{% url 'moulatitcircuit:PrisenchargeUpdate' pk=foo.pk %}">Modifier</a>
                    <a href="{% url 'moulatitcircuit:PrisenchargeDeleteView' pk=foo.pk %}">Supprimer</a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

circuit/templates/circtuit/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

{% endblock %}
{% block content %}
<div class="allcontent">
    <div class="slide_1">
        <p>{{ footer.description1 }}</p>
        <p>{{ footer.description2 }}</p>
        <p>{{ footer.description3 }}</p>
        <div class="block">
            <a href="{{ footer.facebook }}" ><i class="fa fa-facebook"></i></a>
            <a href="{{ footer.Instagram }}" ><i class="fa fa-instagram"></i></a>
        </div>
        <a href="#Nosircuit">Nos Circuit</a>
    </div>
    <div class="mycontainer" id="Nosircuit">
        <div class="circtui_aceuille">
        <h1 style="text-align: center;color: #fff">Nos Circuits</h1>
        <div class="linediveder"></div>
            <div class="row circuit_preview">
                {% for foo in object_list %}
                    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                        <div class="tchep">
                            <div class="imgcontainer">
                            <img src="{{ foo.get_first_image}}" alt="">
                        </div>
                        <div class="circdetail">
                            <h1><a href="{{ foo.get_absolute_url }}">{{ foo.Titre }}</a></h1>
                            <p>{{ foo.Description|linebreaks|truncatewords:20  }}</p>
                        </div>
                        <a href="{{ foo.get_absolute_url }}" class="btneffect">PLus De Détaille</a>
                                                            <div class="linebreak"></div>
                        </div>
                    </div>
                {% endfor %}
                                <div class="linebreak"></div>
            </div>

        </div>
    </div>
    <div id="story">
        <h1 style="text-align: center;color: #fff">Mots</h1>
        <div class="linediveder"></div>

        <p class="textsotr">
            {{ footer.histoire}}
        </p>
    </div>
    <div class="linebreak"></div>
</div>
{% endblock content%}
{% block script %}
<script>
        j=0;
    window.setInterval(function(){
        if(j >= 0 ){
            $('.slide_1 p').fadeOut(0);
            $('.slide_1 p').removeClass('slide_1_effect');

        }
        $('.slide_1 p').eq(j).fadeIn();
        $('.slide_1 p').eq(j).addClass('slide_1_effect');
        if (j === $(".slide_1 p").length-1){
            j=0;
        }else {
            j++;
        }
    }, 2000);
</script>
{% endblock script%}

circuit/templates/circtuit/mots.html
{% extends 'base.html' %}

{% block title %}
    Histoire
{% endblock title %}

{% block content %}
<div class="allcontent mycontainer" style="color: #fff">
    <h1 style="text-align: center">{{ object.titre }}</h1>
    <div class="linediveder"></div>
    <p class="histoiretext">{{ object.mots }}</p>
    {% if user.is_authenticated %}
    <a href="{% url 'moulatitcircuit:UpdateteMot' pk=1 %}">Modifier</a>
    {% endif %}
</div>
{% endblock content %}

circuit/templates/circtuit/myform.html
{% extends 'base.html' %}
{% block title %}
{% endblock title %}
{% block content %}
        <div class="allcontent mycontainer" style="color: #fff">
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
        {% if bookimage_form%}
            {{bookimage_form.as_p }}
        {% endif %}
        <input type="submit">
    </form>
        </div>
{% endblock content %}